
name: C/C++ with Make

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        chmod +x ./build.sh
        ./build.sh
