
name: C/C++ with cmake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: mkdir build
      run: cd build
      run: cmake ..
